--Indeksy dla kluczy g³ównych oraz kolumn oznaczonych jako UNIQUE s¹ generowane automatycznie.

CREATE INDEX idx_participant_last_name ON participant (lastName)
CREATE INDEX idx_employee_last_name ON employee (lastName)
CREATE INDEX idx_order_participantID ON orders (participantID)
CREATE INDEX idx_class_productID ON class (productID)
CREATE INDEX idx_course_productID ON course (productID)
CREATE INDEX idx_webinar_productID ON webinar (productID)
CREATE INDEX idx_convention_productID ON convention (productID)
CREATE INDEX idx_class_productID ON class (productID)
CREATE INDEX idx_course_productID ON course (productID)
CREATE INDEX idx_webinar_productID ON webinar (productID)
CREATE INDEX idx_convention_productID ON convention (productID)
CREATE INDEX idx_class_languageID on class (languageID)
CREATE INDEX idx_company_companyName on company (companyName)
CREATE INDEX idx_convention_classID on convention (classID)
CREATE INDEX idx_courseDetails_name on courseDetails (title)
CREATE INDEX idx_major_name on major (name)
CREATE INDEX idx_meeting_subjectID on meeting (subjectID)
CREATE INDEX idx_meeting_instructorID on meeting (instructorID)
CREATE INDEX idx_meeting_translatorID on meeting (translatorID)
CREATE INDEX idx_room_buildingID on rooms (buildingID)
CREATE INDEX stationaryMeeting_room on stationaryMeeting (roomID)
CREATE INDEX webinarDetails_translator ON webinarDetails (translatorID)
CREATE INDEX webinarDetails_instructor ON webinarDetails (instructorID)
